package utils

const KV_KEY_NUX_DEVICE_ID = "KV_KEY_NUX_DEVICE_ID"
const KV_KEY_NUX_DEVICE_NAME = "KV_KEY_NUX_DEVICE_NAME"

const KV_KEY_NUX_DEVICE_DISKS = "KV_KEY_NUX_DEVICE_DISKS"
const KV_KEY_NUX_DEVICE_DISK_PREFIX = "DISK_"
const KV_KEY_NUX_GALLERY_DIR = "KV_KEY_NUX_GALLERY_DIR"
const KV_KEY_NUX_UPLOAD_DIR = "KV_KEY_NUX_UPLOAD_DIR"
const KV_KEY_NUX_BUCKET_DIRS = "KV_KEY_NUX_BUCKET_DIRS"
const KV_KEY_NUX_PRIVATE_SPACE_SID = "KV_KEY_NUX_PRIVATE_SPACE_SID"
const KV_KEY_NUX_PRIVATE_SPACE_PASSWORD = "KV_KEY_NUX_PRIVATE_SPACE_PASSWORD"
const KV_KEY_NUX_PRIVATE_SPACE_TOKEN = "KV_KEY_NUX_PRIVATE_SPACE_TOKEN"
